"use client"

import Link from "next/link"
import { useState } from "react"

type NotificationItem = { id: string; type: string; title: string; message: string; href: string | null; readAt: Date | null; createdAt: Date; student: { id: string; name: string } }
const formatDate = (date: Date) => new Intl.DateTimeFormat("en-KE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(date))

export default function ParentNotificationsClient({ initialNotifications }: { initialNotifications: NotificationItem[] }) {
  const [notifications, setNotifications] = useState(initialNotifications); const [busy, setBusy] = useState(false); const unread = notifications.filter((item) => !item.readAt).length
  const markAllRead = async () => { setBusy(true); const response = await fetch("/api/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) }); if (response.ok) setNotifications((items) => items.map((item) => ({ ...item, readAt: item.readAt || new Date() }))); setBusy(false) }
  return <div className="space-y-8 animate-fade-in"><section className="relative overflow-hidden rounded-[28px] bg-[#fff4c4] px-7 py-9 sm:px-12 sm:py-12"><div className="absolute -right-12 -top-16 h-64 w-64 rounded-full border-[32px] border-[#f1d976]/60" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-[#746019]">Family updates</p><h1 className="mt-2 text-4xl font-medium tracking-[-.055em] text-[#1c1c1e] sm:text-5xl">Learning alerts</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#746019]">Stay close to the moments that matter: new teacher observations, mastery levels, and progress updates for your children.</p></div>{unread > 0 && <button type="button" disabled={busy} onClick={markAllRead} className="rounded-full bg-[#1c1c1e] px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{busy ? "Updating…" : `Mark ${unread} as read`}</button>}</div></section><section className="space-y-3">{notifications.length === 0 ? <div className="miro-surface p-10 text-center"><p className="text-lg font-semibold">You’re all caught up.</p><p className="mt-2 text-sm text-[#6b6f7e]">New learning updates from teachers will appear here.</p></div> : notifications.map((notification) => <article key={notification.id} className={`miro-surface flex flex-col gap-4 p-5 sm:flex-row sm:items-start sm:justify-between ${notification.readAt ? "opacity-70" : "border-l-4 border-[#ffd02f]"}`}><div className="flex gap-4"><div className={`mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl ${notification.type === "MASTERY_RECORDED" ? "bg-[#c3faf5] text-[#187574]" : "bg-[#e7edff] text-[#4262ff]"}`}>{notification.type === "MASTERY_RECORDED" ? "↗" : "✦"}</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-[#1c1c1e]">{notification.title}</h2>{!notification.readAt && <span className="rounded-full bg-[#ffd02f] px-2 py-0.5 text-[10px] font-bold uppercase text-[#1c1c1e]">New</span>}</div><p className="mt-1 text-sm leading-6 text-[#555a6a]">{notification.message}</p><p className="mt-2 text-xs text-[#8e91a0]">{notification.student.name} · {formatDate(notification.createdAt)}</p></div></div>{notification.href && <Link href={notification.href} className="shrink-0 rounded-full border border-[#e0e2e8] px-3 py-2 text-xs font-semibold text-[#4262ff] hover:bg-[#f7f8fa]">View learner</Link>}</article>)}</section></div>
}
