"use client"

import { useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"

type ApplicableFee = { id?: string; name: string; amount: string }
type FeeStructure = { id: string; schoolId: string; classId: string; term: string; academicYear: string; tuitionFee: number; labFee: number; libraryFee: number; sportsFee: number; examFee: number; otherFees: number; dueDate: string; applicableFees: { id: string; name: string; amount: number }[]; class: { name: string }; school: { name: string } }
type School = { id: string; name: string }
type Class = { id: string; name: string; school: { id: string; name: string } }

export default function EditFeeStructureForm({ structure, schools, classes, userRole }: { structure: FeeStructure; schools: School[]; classes: Class[]; userRole: string }) {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")
  const [form, setForm] = useState({ schoolId: structure.schoolId, classId: structure.classId, term: structure.term, academicYear: structure.academicYear, tuitionFee: String(structure.tuitionFee), labFee: String(structure.labFee), libraryFee: String(structure.libraryFee), sportsFee: String(structure.sportsFee), examFee: String(structure.examFee), otherFees: "0", dueDate: structure.dueDate.slice(0, 10) })
  const [applicableFees, setApplicableFees] = useState<ApplicableFee[]>(structure.applicableFees.length ? structure.applicableFees.map((fee) => ({ id: fee.id, name: fee.name, amount: String(fee.amount) })) : structure.otherFees > 0 ? [{ name: "Other fees", amount: String(structure.otherFees) }] : [])
  const filteredClasses = useMemo(() => classes.filter((item) => item.school.id === form.schoolId), [classes, form.schoolId])
  const fixedTotal = [form.tuitionFee, form.labFee, form.libraryFee, form.sportsFee, form.examFee, form.otherFees].reduce((sum, value) => sum + (Number(value) || 0), 0)
  const total = fixedTotal + applicableFees.reduce((sum, fee) => sum + (Number(fee.amount) || 0), 0)
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const updateApplicableFee = (index: number, key: keyof ApplicableFee, value: string) => setApplicableFees((current) => current.map((fee, feeIndex) => feeIndex === index ? { ...fee, [key]: value } : fee))
  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault(); setLoading(true); setError("")
    try {
      const response = await fetch(`/api/fees/structures/${structure.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, applicableFees }) })
      const result = await response.json()
      if (!response.ok) throw new Error(result.error || "Unable to update fee structure")
      router.push(`/dashboard/fees/structures/${structure.id}`); router.refresh()
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update fee structure"); setLoading(false) }
  }
  const input = (label: string, key: keyof typeof form, type = "number") => <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#6b6f7e]">{label}</span><input type={type} required={key === "tuitionFee" || key === "term" || key === "academicYear" || key === "dueDate"} min={type === "number" ? "0" : undefined} step={type === "number" ? "0.01" : undefined} value={form[key]} onChange={(event) => update(key, event.target.value)} className="w-full rounded-lg border border-[#c7cad5] bg-white px-4 py-3 text-sm text-[#1c1c1e] outline-none transition focus:border-[#4262ff] focus:ring-2 focus:ring-[#e7edff]" /></label>
  return <form onSubmit={handleSubmit} className="space-y-6">
    <section className="miro-surface p-6 sm:p-8"><div className="mb-7"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#8e91a0]">Plan details</p><h2 className="mt-2 text-2xl font-medium text-[#1c1c1e]">Where this structure applies</h2></div><div className="grid gap-5 md:grid-cols-2">{userRole === "SUPER_ADMIN" && <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#6b6f7e]">School</span><select value={form.schoolId} onChange={(event) => setForm((current) => ({ ...current, schoolId: event.target.value, classId: "" }))} className="w-full rounded-lg border border-[#c7cad5] bg-white px-4 py-3 text-sm text-[#1c1c1e] outline-none focus:border-[#4262ff]"><option value="">Choose a school</option>{schools.map((school) => <option key={school.id} value={school.id}>{school.name}</option>)}</select></label>}<label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#6b6f7e]">Class</span><select required value={form.classId} onChange={(event) => update("classId", event.target.value)} className="w-full rounded-lg border border-[#c7cad5] bg-white px-4 py-3 text-sm text-[#1c1c1e] outline-none focus:border-[#4262ff]"><option value="">Choose a class</option>{filteredClasses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-[.14em] text-[#6b6f7e]">Term</span><select required value={form.term} onChange={(event) => update("term", event.target.value)} className="w-full rounded-lg border border-[#c7cad5] bg-white px-4 py-3 text-sm text-[#1c1c1e] outline-none focus:border-[#4262ff]"><option value="">Choose a term</option>{["Term 1", "Term 2", "Term 3", "Semester 1", "Semester 2"].map((term) => <option key={term}>{term}</option>)}</select></label>{input("Academic year", "academicYear", "number")}{input("Due date", "dueDate", "date")}</div></section>
    <section className="miro-surface p-6 sm:p-8"><div className="mb-7"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#8e91a0]">Plan makeup</p><h2 className="mt-2 text-2xl font-medium text-[#1c1c1e]">Core fees</h2></div><div className="grid gap-5 md:grid-cols-2">{input("Tuition fee (KES)", "tuitionFee")}{input("Laboratory fee (KES)", "labFee")}{input("Library fee (KES)", "libraryFee")}{input("Sports fee (KES)", "sportsFee")}{input("Exam fee (KES)", "examFee")}</div></section>
    <section className="miro-surface p-6 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-[#8e91a0]">Flexible charges</p><h2 className="mt-2 text-2xl font-medium text-[#1c1c1e]">Other applicable fees</h2><p className="mt-2 max-w-xl text-sm text-[#6b6f7e]">Add named charges such as transport, meals, uniforms, trips or technology. Each item is saved separately.</p></div><button type="button" onClick={() => setApplicableFees((current) => [...current, { name: "", amount: "" }])} className="miro-pill shrink-0 bg-[#c3faf5] px-4 py-2.5 text-sm font-medium text-[#187574]">+ Add fee</button></div><div className="mt-7 space-y-3">{applicableFees.length === 0 && <div className="rounded-xl border border-dashed border-[#c7cad5] px-5 py-8 text-center text-sm text-[#8e91a0]">No additional charges yet. Add one above if this plan needs it.</div>}{applicableFees.map((fee, index) => <div key={fee.id || `new-${index}`} className="grid gap-3 rounded-xl bg-[#f7f8fa] p-3 sm:grid-cols-[1fr_180px_auto] sm:items-end"><label className="block"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[.14em] text-[#8e91a0]">Fee name</span><input required value={fee.name} onChange={(event) => updateApplicableFee(index, "name", event.target.value)} placeholder="e.g. Transport" className="w-full rounded-lg border border-[#c7cad5] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#4262ff]" /></label><label className="block"><span className="mb-2 block text-[10px] font-semibold uppercase tracking-[.14em] text-[#8e91a0]">Amount (KES)</span><input required type="number" min="0" step="0.01" value={fee.amount} onChange={(event) => updateApplicableFee(index, "amount", event.target.value)} placeholder="0.00" className="w-full rounded-lg border border-[#c7cad5] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#4262ff]" /></label><button type="button" onClick={() => setApplicableFees((current) => current.filter((_, feeIndex) => feeIndex !== index))} className="px-3 py-2.5 text-sm font-medium text-[#600000] hover:underline">Remove</button></div>)}</div></section>
    <div className="flex items-center justify-between rounded-[16px] bg-[#fff4c4] px-5 py-4"><span className="text-sm font-medium text-[#746019]">Updated total</span><span className="font-mono text-2xl font-medium text-[#746019]">KES {total.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span></div>
    {error && <div className="rounded-lg border border-[#ffc6c6] bg-[#fff1f1] px-4 py-3 text-sm font-medium text-[#600000]">{error}</div>}<div className="flex flex-wrap gap-3"><button type="submit" disabled={loading} className="miro-pill bg-[#1c1c1e] px-5 py-3 text-sm font-medium text-white transition hover:bg-[#2c2c34] disabled:opacity-50">{loading ? "Saving…" : "Save changes →"}</button><Link href={`/dashboard/fees/structures/${structure.id}`} className="miro-pill border border-[#c7cad5] px-5 py-3 text-sm font-medium text-[#1c1c1e]">Cancel</Link></div>
  </form>
}
