import { auth } from "@/lib/auth-config"
import { redirect } from "next/navigation"
import Link from "next/link"
import { prisma } from "@/lib/prisma"
import StatCard from "@/components/ui/StatCard"

const actions = [
  { href: "/dashboard/students", label: "Students", detail: "View records and performance", number: "01", roles: ["SUPER_ADMIN", "SCHOOL_ADMIN"] },
  { href: "/dashboard/assessments/new", label: "New assessment", detail: "Set up a score entry", number: "02", roles: ["SUPER_ADMIN", "SCHOOL_ADMIN"] },
  { href: "/dashboard/attendance", label: "Take attendance", detail: "Mark today in seconds", number: "03", roles: ["SUPER_ADMIN", "SCHOOL_ADMIN", "TEACHER"] },
  { href: "/dashboard/analysis", label: "Insights", detail: "Turn results into action", number: "04", roles: ["SUPER_ADMIN", "SCHOOL_ADMIN", "TEACHER"] },
]

export default async function DashboardPage() {
  const session = await auth(); if (!session) redirect("/login"); if (session.user.role === "TEACHER") redirect("/dashboard/teacher"); if (session.user.role === "PARENT") redirect("/dashboard/parent")
  const schoolFilter = session.user.role === "SCHOOL_ADMIN" && session.user.schoolId ? { schoolId: session.user.schoolId } : {}
  const [totalStudents, activeClasses, totalAssessments, totalAnalyses] = await Promise.all([prisma.student.count({ where: schoolFilter }), prisma.class.count({ where: schoolFilter }), prisma.assessment.count({ where: schoolFilter }), prisma.performanceAnalysis.count({ where: session.user.role === "SCHOOL_ADMIN" && session.user.schoolId ? { student: { schoolId: session.user.schoolId } } : {} })])
  const visibleActions = actions.filter((action) => action.roles.includes(session.user.role || ""))
  return <div className="space-y-12 animate-fade-in">
    <section className="border-b border-slate-200 pb-9"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-4 text-[11px] font-bold uppercase tracking-[.22em] text-blue-600">Monday · 28 September 2026</p><h1 className="display-serif text-4xl leading-tight text-slate-950 sm:text-6xl">A clear view of<br /><em className="text-blue-600">what matters.</em></h1><p className="mt-5 max-w-lg text-sm leading-6 text-slate-500">Welcome back, {session.user.name?.split(" ")[0]}. Here’s the current picture across your school.</p></div><div className="flex items-center gap-3 text-right"><span className="h-2 w-2 rounded-full bg-emerald-500" /><span className="text-xs font-semibold text-slate-500">Data updated just now</span></div></div></section>
    <section><div className="mb-5 flex items-end justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-slate-400">The numbers</p><h2 className="mt-2 text-lg font-bold text-slate-950">School at a glance</h2></div></div><div className="grid grid-cols-2 divide-x divide-slate-200 border-y border-slate-200 bg-white xl:grid-cols-4"><StatCard title="Students" value={totalStudents} color="blue" href="/dashboard/students" /><StatCard title="Classes" value={activeClasses} color="green" /><StatCard title="Assessments" value={totalAssessments} color="purple" href="/dashboard/assessments" /><StatCard title="AI analyses" value={totalAnalyses} color="orange" href="/dashboard/analysis" /></div></section>
    <section className="grid gap-12 xl:grid-cols-[1.2fr_.8fr]"><div><div className="mb-5 flex items-end justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-slate-400">Next actions</p><h2 className="mt-2 text-lg font-bold text-slate-950">Keep the work moving</h2></div></div><div className="divide-y divide-slate-200 border-y border-slate-200">{visibleActions.map((action) => <Link key={action.href} href={action.href} className="group flex items-center gap-5 py-4 transition hover:bg-white"><span className="font-mono text-xs font-bold text-slate-400">{action.number}</span><span className="flex-1"><strong className="block text-sm font-bold text-slate-900">{action.label}</strong><small className="mt-1 block text-xs text-slate-500">{action.detail}</small></span><span className="text-sm text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-600">→</span></Link>)}</div></div><div className="border-t border-slate-200 pt-5"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-slate-400">Workspace status</p><h2 className="mt-2 text-lg font-bold text-slate-950">Everything is in order.</h2><div className="mt-7 space-y-5"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><span className="text-sm text-slate-500">Students enrolled</span><strong className="font-mono text-sm text-slate-950">{totalStudents}</strong></div><div className="flex items-center justify-between border-b border-slate-200 pb-4"><span className="text-sm text-slate-500">Classes running</span><strong className="font-mono text-sm text-slate-950">{activeClasses}</strong></div><div className="flex items-center justify-between border-b border-slate-200 pb-4"><span className="text-sm text-slate-500">Analyses generated</span><strong className="font-mono text-sm text-slate-950">{totalAnalyses}</strong></div><p className="pt-1 text-xs leading-5 text-slate-400">Your workspace is connected and ready for the next update.</p></div></div></section>
  </div>
}
